<?php

use Nacosvel\NacosClient\Console\CreateNamespaceRequest;
use Nacosvel\NacosClient\Console\DeleteNamespaceRequest;
use Nacosvel\NacosClient\Console\NamespaceListRequest;
use Nacosvel\NacosClient\Console\NamespaceRequest;
use Nacosvel\NacosClient\Console\UpdateNamespaceRequest;
use Nacosvel\NacosClient\NacosService;
use PHPUnit\Framework\TestCase;

class ConsoleNamespaceTest extends TestCase
{
    protected NacosService $nacosService;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->nacosService = new NacosService('http://127.0.0.1:8848');
    }

    /**
     * 创建命名空间v1
     *
     * @return void
     */
    public function testCreateNamespaceRequestV1Success(): void
    {
        $request  = new CreateNamespaceRequest();
        $data     = $request->v1('testv1-123', 'testv1');
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

    /**
     * 创建命名空间v1
     *
     * @return void
     */
    public function testCreateNamespaceRequestV1Error(): void
    {
        $request  = new CreateNamespaceRequest();
        $data     = $request->v1('testv1-123', 'testv1');
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

    /**
     * 创建命名空间v2
     *
     * @return void
     */
    public function testCreateNamespaceRequestV2Success(): void
    {
        $request  = new CreateNamespaceRequest();
        $data     = $request->v2('testv2-123', 'testv2');
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

    /**
     * 创建命名空间v2
     *
     * @return void
     */
    public function testCreateNamespaceRequestV2Error(): void
    {
        $request  = new CreateNamespaceRequest();
        $data     = $request->v2('testv2-123', 'testv2');
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

    /**
     * 修改命名空间v1
     *
     * @return void
     */
    public function testUpdateNamespaceRequestV1(): void
    {
        $request  = new UpdateNamespaceRequest();
        $data     = $request->v1('testv1-123', 'testv1-update', '测试v1修改命名空间名称');
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

    /**
     * 修改命名空间v2
     *
     * @return void
     */
    public function testUpdateNamespaceRequestV2(): void
    {
        $request  = new CreateNamespaceRequest();
        $data     = $request->v2('testv2-123', 'testv2-update');
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

    /**
     * 查询命名空间列表v1
     *
     * @return void
     */
    public function testNamespaceListRequestV1(): void
    {
        $request  = new NamespaceListRequest();
        $data     = $request->v1();
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

    /**
     * 查询命名空间列表v2
     *
     * @return void
     */
    public function testNamespaceListRequestV2(): void
    {
        $request  = new NamespaceListRequest();
        $data     = $request->v2();
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

    /**
     * 查询具体命名空间v2
     *
     * @return void
     */
    public function testNamespaceRequest(): void
    {
        $request  = new NamespaceRequest();
        $data     = $request->v2('testv2-123');
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

    /**
     * 删除命名空间v1
     *
     * @return void
     */
    public function testDeleteNamespaceRequestV1(): void
    {
        $request  = new DeleteNamespaceRequest();
        $data     = $request->v1('testv1-123');
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

    /**
     * 删除命名空间v2
     *
     * @return void
     */
    public function testDeleteNamespaceRequestV2(): void
    {
        $request  = new DeleteNamespaceRequest();
        $data     = $request->v2('testv2-123');
        $response = $this->nacosService->execute($data);
        var_dump($response->raw());
        var_dump($response->response());
        $this->assertTrue(is_array($response->response()));
    }

}
