name: subtree-matrix

on: [ push ]

jobs:
  sync-downstream:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        path:
          - composer
          - console
          - container-interop
          - feign
          - helper
          - load-balancer
          - nacos-client
          - nacos-config
          - nacos-discover
          - nacos-sdk-php
          - open-http
          - package
          - rooster

    name: Update downstream ${{ matrix.path }} package

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          repo: 'nacosvel/${{ matrix.path }}'
          path: '${{ matrix.path }}'
          force: true
