name: subtree-matrix

on: [ push ]

permissions: write-all

jobs:
  sync-downstream:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        path:
          - composer
          - console
          - container-interop

    name: Update downstream package

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update downstream ${{ matrix.path }} package
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git subtree push --prefix=${{ matrix.path }} https://${{ secrets.PAT_TOKEN }}@github.com/nacosvel/${{ matrix.path }}.git main

