name: subtree-matrix

on: [ push ]

permissions: write-all

jobs:
  sync-downstream:

    runs-on: ubuntu-latest

    name: Update downstream package

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          repo: 'nacosvel/composer'
          path: 'composer'
